name: 'Hello World'
description: 'Greet someone'
inputs:
    who-to-greet:  # id of input
        description: 'Who to greet'
        required: true
        default: 'World'
outputs:
    random-number:
        description: "Random number"
        value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
    using: "composite"
    steps:
        - run: echo Hello ${{ inputs.who-to-greet }}.
          shell: bash
        - id: random-number-generator
          run: echo "::set-output name=random-id::$(echo $RANDOM)"
          shell: bash
        - id: git-data
          shell: bash
          run: |
            printf "The repo in use is %s and is owned by %s\n" "${{ github.repository }}" "${{ github.repository_owner }}"
            echo "::set-output name=foo::${{ github.repository }}"
        - id: hand-off-to-script
          run: |
            printf "I was handed %d and will now give it to the script.\n" "${{ steps.random-number-generator.outputs.random-id }}"
            printf "foo is %s" "${{ steps.git-data.outputs.foo }}"
            ${{ github.action_path }}/foo.sh ${{ steps.random-number-generator.outputs.random-id }}
          shell: bash
