name: 'Hello World'
description: 'Greet someone'
inputs:
    who-to-greet:  # id of input
        description: 'Who to greet'
        required: true
        default: 'World'
outputs:
    random-number:
        description: "Random number"
        value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
    using: "composite"
    steps:
        - run: echo Hello ${{ inputs.who-to-greet }}.
          shell: bash
        - id: barfoo
          shell: bash
          run: |
            echo "::set-output name=bar::foobar"
        - id: random-number-generator
          run: RAND="${RANDOM}"; echo "::set-output name=random-id::$(echo ${RAND})"; echo "rand=${RAND}" >> $GITHUB_ENV
          shell: bash
        - id: git-data
          shell: bash
          run: |
            printf "The repo in use is %s and is owned by %s\n" "${{ github.repository }}" "${{ github.repository_owner }}"
            echo "foo=barfoo" >> $GITHUB_ENV
        - id: hand-off-to-script
          run: |
            printf "from the earlier step, they created the value '%s'\n" "${{ steps.barfoo.outputs.bar }}"
            printf "I was handed %d and will now give it to the script.\n" "${{ env.rand }}"
            printf "foo is %s" "${{ env.foo }}"
            ${{ github.action_path }}/foo.sh ${{ env.rand }}
          shell: bash
